// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file is part of OpenAPI / Swagger Documentation for QuickWork API.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "QuickWork Support Team",
            "email": "support@quickwork.vn"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/register": {
            "post": {
                "tags": ["Authentication"],
                "summary": "Đăng ký tài khoản người dùng mới (Student / Business)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["email", "password", "role"],
                            "properties": {
                                "email": { "type": "string", "example": "student0@gmail.com" },
                                "password": { "type": "string", "example": "12345678" },
                                "role": { "type": "string", "example": "student" },
                                "full_name": { "type": "string", "example": "Nguyễn Văn Minh" }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": { "description": "Tạo tài khoản thành công" },
                    "400": { "description": "Email đã tồn tại hoặc dữ liệu không hợp lệ" }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "tags": ["Authentication"],
                "summary": "Đăng nhập hệ thống & Lấy JWT Bearer Token",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["email", "password"],
                            "properties": {
                                "email": { "type": "string", "example": "student0@gmail.com" },
                                "password": { "type": "string", "example": "12345678" }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": { "description": "Đăng nhập thành công, trả về token và user info" },
                    "401": { "description": "Email hoặc mật khẩu không chính xác" }
                }
            }
        },
        "/api/users/me": {
            "get": {
                "tags": ["Authentication"],
                "summary": "Lấy thông tin tài khoản hiện tại",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Thông tin User hiện tại" },
                    "401": { "description": "Chưa đăng nhập" }
                }
            }
        },
        "/api/profile/student": {
            "get": {
                "tags": ["Profile Management"],
                "summary": "Lấy hồ sơ cá nhân Sinh viên",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Hồ sơ Student" }
                }
            },
            "put": {
                "tags": ["Profile Management"],
                "summary": "Cập nhật hồ sơ Sinh viên & Tải lên file CV PDF",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "full_name": { "type": "string", "example": "Nguyễn Văn Minh" },
                                "phone": { "type": "string", "example": "0987654321" },
                                "skills": { "type": "string", "example": "Go, Vue, JavaScript" },
                                "cv_url": { "type": "string", "example": "/uploads/cvs/my_cv.pdf" }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": { "description": "Cập nhật thành công" }
                }
            }
        },
        "/api/profile/business": {
            "get": {
                "tags": ["Profile Management"],
                "summary": "Lấy hồ sơ doanh nghiệp",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Hồ sơ Business" }
                }
            },
            "put": {
                "tags": ["Profile Management"],
                "summary": "Cập nhật thông tin Doanh nghiệp",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "company_name": { "type": "string", "example": "FPT Software" },
                                "website": { "type": "string", "example": "https://fpt-software.com" },
                                "address": { "type": "string", "example": "Hà Nội" }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": { "description": "Cập nhật doanh nghiệp thành công" }
                }
            }
        },
        "/api/jobs": {
            "get": {
                "tags": ["Job Board"],
                "summary": "Danh sách công việc đang đăng tuyển (Có bộ lọc tìm kiếm)",
                "produces": ["application/json"],
                "parameters": [
                    { "name": "search", "in": "query", "type": "string", "description": "Từ khóa tìm kiếm" },
                    { "name": "category", "in": "query", "type": "string", "description": "Lọc theo Ngành nghề" },
                    { "name": "location", "in": "query", "type": "string", "description": "Lọc theo Địa điểm" }
                ],
                "responses": {
                    "200": { "description": "Danh sách công việc" }
                }
            },
            "post": {
                "tags": ["Job Board"],
                "summary": "Doanh nghiệp đăng tin tuyển dụng mới",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["title", "description", "salary"],
                            "properties": {
                                "title": { "type": "string", "example": "Kỹ sư Golang Backend" },
                                "description": { "type": "string", "example": "Phát triển hệ thống microservices" },
                                "category": { "type": "string", "example": "IT" },
                                "salary": { "type": "number", "example": 15000000 },
                                "location": { "type": "string", "example": "Hà Nội" }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": { "description": "Tạo bài tuyển dụng thành công" }
                }
            }
        },
        "/api/jobs/{id}": {
            "get": {
                "tags": ["Job Board"],
                "summary": "Xem chi tiết 1 tin tuyển dụng theo ID",
                "produces": ["application/json"],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "integer", "example": 2 }
                ],
                "responses": {
                    "200": { "description": "Chi tiết công việc" },
                    "404": { "description": "Không tìm thấy công việc" }
                }
            }
        },
        "/api/ai/evaluate-cv": {
            "post": {
                "tags": ["AI Services"],
                "summary": "AI Đánh giá & Chấm điểm CV Sinh viên (Gemini / Heuristic)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "cv_url": { "type": "string", "example": "/uploads/cvs/1786439208_Resume.pdf" }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": { "description": "Báo cáo phân tích CV AI chi tiết" }
                }
            }
        },
        "/api/ai/match-job": {
            "post": {
                "tags": ["AI Services"],
                "summary": "AI Đánh giá % Phù hợp giữa Sinh viên & Công việc (Match Job)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["job_id"],
                            "properties": {
                                "job_id": { "type": "integer", "example": 2 }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": { "description": "Kết quả % Match Score và lý do chi tiết" }
                }
            }
        },
        "/api/ai/recommended-jobs": {
            "get": {
                "tags": ["AI Services"],
                "summary": "AI Gợi ý danh sách công việc phù hợp nhất cho Sinh viên (Redis Cache)",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Danh sách Job được AI xếp hạng" }
                }
            }
        },
        "/api/ai/generate-job": {
            "post": {
                "tags": ["AI Services"],
                "summary": "AI Tự động soạn thảo Bài tuyển dụng (JD) cho Doanh nghiệp",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["title"],
                            "properties": {
                                "title": { "type": "string", "example": "Lập trình viên Golang" }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": { "description": "Nội dung bài tuyển dụng hoàn chỉnh" }
                }
            }
        },
        "/api/applications": {
            "post": {
                "tags": ["Applications"],
                "summary": "Sinh viên Nộp hồ sơ ứng tuyển công việc",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["job_id"],
                            "properties": {
                                "job_id": { "type": "integer", "example": 2 },
                                "cover_letter": { "type": "string", "example": "Em rất mong muốn ứng tuyển vị trí này..." }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": { "description": "Ứng tuyển thành công" }
                }
            }
        },
        "/api/applications/my-applications": {
            "get": {
                "tags": ["Applications"],
                "summary": "Danh sách các đơn ứng tuyển của Sinh viên",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Danh sách ứng tuyển" }
                }
            }
        },
        "/api/applications/employer": {
            "get": {
                "tags": ["Applications"],
                "summary": "Doanh nghiệp xem danh sách ứng viên nộp hồ sơ",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Danh sách ứng viên nộp bài" }
                }
            }
        },
        "/api/wallet/me": {
            "get": {
                "tags": ["Wallet & Escrow"],
                "summary": "Xem số dư Ví tiền QuickWork hiện tại",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Số dư tài khoản ví" }
                }
            }
        },
        "/api/wallet/deposit": {
            "post": {
                "tags": ["Wallet & Escrow"],
                "summary": "Nạp tiền vào Ví QuickWork",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["amount"],
                            "properties": {
                                "amount": { "type": "number", "example": 500000 }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": { "description": "Nạp tiền thành công" }
                }
            }
        },
        "/api/attendance/check-in": {
            "post": {
                "tags": ["Attendance & Tracking"],
                "summary": "Sinh viên Điểm danh Check-in ca làm việc",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Check-in thành công" }
                }
            }
        },
        "/api/attendance/check-out": {
            "post": {
                "tags": ["Attendance & Tracking"],
                "summary": "Sinh viên Điểm danh Check-out kết thúc ca làm việc",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Check-out và ghi nhận thời gian làm" }
                }
            }
        },
        "/api/chat/history": {
            "get": {
                "tags": ["Chat & Communication"],
                "summary": "Lịch sử tin nhắn trao đổi",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Danh sách tin nhắn chat" }
                }
            }
        },
        "/api/admin/dashboard/stats": {
            "get": {
                "tags": ["Admin Operations"],
                "summary": "Thống kê tổng quan hệ thống dành cho Admin",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Thống kê sinh viên, doanh nghiệp, việc làm, doanh thu" }
                }
            }
        },
        "/api/admin/businesses/pending": {
            "get": {
                "tags": ["Admin Operations"],
                "summary": "Danh sách doanh nghiệp chờ duyệt tài khoản",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Danh sách doanh nghiệp chờ phê duyệt" }
                }
            }
        },
        "/api/admin/businesses": {
            "get": {
                "tags": ["Admin Operations"],
                "summary": "Admin Quản lý Danh sách Doanh nghiệp (Có lọc Tên/MST/Email & Trạng thái)",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    { "name": "search", "in": "query", "type": "string", "description": "Từ khóa tìm kiếm Tên công ty, MST hoặc Email" },
                    { "name": "status", "in": "query", "type": "string", "description": "Trạng thái approved, pending, locked" }
                ],
                "responses": {
                    "200": { "description": "Danh sách doanh nghiệp kèm phân trang" }
                }
            }
        },
        "/api/admin/businesses/{id}/status": {
            "put": {
                "tags": ["Admin Operations"],
                "summary": "Admin Khóa (locked) hoặc Mở khóa (approved) Tài khoản Doanh nghiệp",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "integer", "example": 1 },
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["status"],
                            "properties": {
                                "status": { "type": "string", "example": "locked" }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": { "description": "Đã cập nhật trạng thái doanh nghiệp thành công" }
                }
            }
        },
        "/api/admin/tickets": {
            "get": {
                "tags": ["Admin Operations"],
                "summary": "Admin Quản lý Danh sách Ticket Khiếu nại",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    { "name": "status", "in": "query", "type": "string", "description": "Lọc trạng thái pending, resolved, rejected" }
                ],
                "responses": {
                    "200": { "description": "Danh sách ticket khiếu nại" }
                }
            }
        },
        "/api/admin/tickets/{id}/resolve": {
            "put": {
                "tags": ["Admin Operations"],
                "summary": "Admin Ban hành Phán quyết Giải quyết Tranh chấp",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "integer", "example": 1 },
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["verdict"],
                            "properties": {
                                "verdict": { "type": "string", "example": "Chấp nhận bồi thường tiền ca làm cho sinh viên" },
                                "status": { "type": "string", "example": "resolved" }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": { "description": "Đã ban hành phán quyết xử lý thành công" }
                }
            }
        },
        "/api/admin/categories": {
            "get": {
                "tags": ["Admin Operations"],
                "summary": "Lấy danh sách Ngành nghề tuyển dụng",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Danh sách Ngành nghề" }
                }
            },
            "post": {
                "tags": ["Admin Operations"],
                "summary": "Admin Tạo Ngành nghề tuyển dụng mới",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["name"],
                            "properties": {
                                "name": { "type": "string", "example": "Lập trình Trí tuệ nhân tạo (AI/ML)" },
                                "description": { "type": "string", "example": "Machine Learning, Deep Learning, Python" }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": { "description": "Tạo ngành nghề mới thành công" }
                }
            }
        },
        "/api/admin/skills": {
            "get": {
                "tags": ["Admin Operations"],
                "summary": "Lấy danh sách Kỹ năng chuẩn hóa",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "responses": {
                    "200": { "description": "Danh sách Kỹ năng" }
                }
            },
            "post": {
                "tags": ["Admin Operations"],
                "summary": "Admin Tạo Kỹ năng chuẩn hóa mới (Phục vụ AI Match Job)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["name"],
                            "properties": {
                                "name": { "type": "string", "example": "PyTorch" },
                                "category": { "type": "string", "example": "AI/ML" }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": { "description": "Tạo kỹ năng thành công" }
                }
            }
        },
        "/api/admin/students": {
            "get": {
                "tags": ["Admin Operations"],
                "summary": "Admin Quản lý Danh sách Sinh viên (Có lọc Tên/Email/SĐT & Trạng thái)",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    { "name": "search", "in": "query", "type": "string", "description": "Từ khóa tìm kiếm Tên, Email hoặc SĐT" },
                    { "name": "status", "in": "query", "type": "string", "description": "Trạng thái approved hoặc locked" }
                ],
                "responses": {
                    "200": { "description": "Danh sách sinh viên kèm phân trang" }
                }
            }
        },
        "/api/admin/students/{id}": {
            "get": {
                "tags": ["Admin Operations"],
                "summary": "Admin Xem Chi tiết Hồ sơ Sinh viên theo ID",
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "integer", "example": 1 }
                ],
                "responses": {
                    "200": { "description": "Thông tin chi tiết sinh viên" },
                    "404": { "description": "Không tìm thấy sinh viên" }
                }
            }
        },
        "/api/admin/students/{id}/status": {
            "put": {
                "tags": ["Admin Operations"],
                "summary": "Admin Khóa (locked) hoặc Mở khóa (approved) Tài khoản Sinh viên",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "integer", "example": 1 },
                    {
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["status"],
                            "properties": {
                                "status": { "type": "string", "example": "locked" }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": { "description": "Đã cập nhật trạng thái sinh viên thành công" }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Nhập chuỗi JWT token hoặc 'Bearer {token}' để xác thực"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "QuickWork System Full API Documentation",
	Description:      "Tài liệu tương tác OpenAPI / Swagger toàn bộ tất cả 11 Phân hệ API của Hệ thống QuickWork",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
